export const mockData = [
  {
    location: {
      name: 'Belgrade',
      region: '',
      country: 'Belgium',
      lat: 50.47,
      lon: 4.83,
      tz_id: 'Europe/Brussels',
      localtime_epoch: 1634134307,
      localtime: '2021-10-13 16:11',
    },
    current: {
      last_updated_epoch: 1634130000,
      last_updated: '2021-10-13 15:00',
      temp_c: 11.0,
      temp_f: 51.8,
      is_day: 1,
      condition: {
        text: 'Partly cloudy',
        icon: '//cdn.weatherapi.com/weather/64x64/day/116.png',
        code: 1003,
      },
      wind_mph: 8.1,
      wind_kph: 13.0,
      wind_degree: 310,
      wind_dir: 'NW',
      pressure_mb: 1027.0,
      pressure_in: 30.33,
      precip_mm: 0.0,
      precip_in: 0.0,
      humidity: 76,
      cloud: 75,
      feelslike_c: 9.3,
      feelslike_f: 48.8,
      vis_km: 10.0,
      vis_miles: 6.0,
      uv: 3.0,
      gust_mph: 9.8,
      gust_kph: 15.8,
    },
    forecast: {
      forecastday: [
        {
          date: '2021-10-13',
          date_epoch: 1634083200,
          day: {
            maxtemp_c: 13.4,
            maxtemp_f: 56.1,
            mintemp_c: 4.9,
            mintemp_f: 40.8,
            avgtemp_c: 8.3,
            avgtemp_f: 47.0,
            maxwind_mph: 9.6,
            maxwind_kph: 15.5,
            totalprecip_mm: 0.5,
            totalprecip_in: 0.02,
            avgvis_km: 10.0,
            avgvis_miles: 6.0,
            avghumidity: 82.0,
            daily_will_it_rain: 1,
            daily_chance_of_rain: 77,
            daily_will_it_snow: 0,
            daily_chance_of_snow: 0,
            condition: {
              text: 'Patchy rain possible',
              icon: '//cdn.weatherapi.com/weather/64x64/day/176.png',
              code: 1063,
            },
            uv: 2.0,
          },
          astro: {
            sunrise: '08:00 AM',
            sunset: '06:53 PM',
            moonrise: '04:27 PM',
            moonset: 'No moonset',
            moon_phase: 'Waxing Gibbous',
            moon_illumination: '55',
          },
          hour: [
            {
              time_epoch: 1634076000,
              time: '2021-10-13 00:00',
              temp_c: 5.3,
              temp_f: 41.5,
              is_day: 0,
              condition: {
                text: 'Clear',
                icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
                code: 1000,
              },
              wind_mph: 4.3,
              wind_kph: 6.8,
              wind_degree: 345,
              wind_dir: 'NNW',
              pressure_mb: 1024.0,
              pressure_in: 30.23,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 92,
              cloud: 23,
              feelslike_c: 3.8,
              feelslike_f: 38.8,
              windchill_c: 3.8,
              windchill_f: 38.8,
              heatindex_c: 5.3,
              heatindex_f: 41.5,
              dewpoint_c: 4.1,
              dewpoint_f: 39.4,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 8.9,
              gust_kph: 14.4,
              uv: 1.0,
            },
            {
              time_epoch: 1634079600,
              time: '2021-10-13 01:00',
              temp_c: 4.9,
              temp_f: 40.8,
              is_day: 0,
              condition: {
                text: 'Cloudy',
                icon: '//cdn.weatherapi.com/weather/64x64/night/119.png',
                code: 1006,
              },
              wind_mph: 3.1,
              wind_kph: 5.0,
              wind_degree: 326,
              wind_dir: 'NNW',
              pressure_mb: 1024.0,
              pressure_in: 30.24,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 92,
              cloud: 68,
              feelslike_c: 4.0,
              feelslike_f: 39.2,
              windchill_c: 4.0,
              windchill_f: 39.2,
              heatindex_c: 4.9,
              heatindex_f: 40.8,
              dewpoint_c: 3.7,
              dewpoint_f: 38.7,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 6.5,
              gust_kph: 10.4,
              uv: 1.0,
            },
            {
              time_epoch: 1634083200,
              time: '2021-10-13 02:00',
              temp_c: 5.4,
              temp_f: 41.7,
              is_day: 0,
              condition: {
                text: 'Overcast',
                icon: '//cdn.weatherapi.com/weather/64x64/night/122.png',
                code: 1009,
              },
              wind_mph: 2.9,
              wind_kph: 4.7,
              wind_degree: 308,
              wind_dir: 'NW',
              pressure_mb: 1024.0,
              pressure_in: 30.25,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 90,
              cloud: 92,
              feelslike_c: 4.7,
              feelslike_f: 40.5,
              windchill_c: 4.7,
              windchill_f: 40.5,
              heatindex_c: 5.4,
              heatindex_f: 41.7,
              dewpoint_c: 3.9,
              dewpoint_f: 39.0,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 6.0,
              gust_kph: 9.7,
              uv: 1.0,
            },
            {
              time_epoch: 1634086800,
              time: '2021-10-13 03:00',
              temp_c: 6.5,
              temp_f: 43.7,
              is_day: 0,
              condition: {
                text: 'Overcast',
                icon: '//cdn.weatherapi.com/weather/64x64/night/122.png',
                code: 1009,
              },
              wind_mph: 3.4,
              wind_kph: 5.4,
              wind_degree: 279,
              wind_dir: 'W',
              pressure_mb: 1025.0,
              pressure_in: 30.26,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 88,
              cloud: 93,
              feelslike_c: 5.6,
              feelslike_f: 42.1,
              windchill_c: 5.6,
              windchill_f: 42.1,
              heatindex_c: 6.5,
              heatindex_f: 43.7,
              dewpoint_c: 4.7,
              dewpoint_f: 40.5,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 6.5,
              gust_kph: 10.4,
              uv: 1.0,
            },
            {
              time_epoch: 1634090400,
              time: '2021-10-13 04:00',
              temp_c: 6.8,
              temp_f: 44.2,
              is_day: 0,
              condition: {
                text: 'Overcast',
                icon: '//cdn.weatherapi.com/weather/64x64/night/122.png',
                code: 1009,
              },
              wind_mph: 4.7,
              wind_kph: 7.6,
              wind_degree: 279,
              wind_dir: 'W',
              pressure_mb: 1025.0,
              pressure_in: 30.26,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 89,
              cloud: 100,
              feelslike_c: 5.4,
              feelslike_f: 41.7,
              windchill_c: 5.4,
              windchill_f: 41.7,
              heatindex_c: 6.8,
              heatindex_f: 44.2,
              dewpoint_c: 5.2,
              dewpoint_f: 41.4,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 8.5,
              gust_kph: 13.7,
              uv: 1.0,
            },
            {
              time_epoch: 1634094000,
              time: '2021-10-13 05:00',
              temp_c: 7.0,
              temp_f: 44.6,
              is_day: 0,
              condition: {
                text: 'Cloudy',
                icon: '//cdn.weatherapi.com/weather/64x64/night/119.png',
                code: 1006,
              },
              wind_mph: 4.5,
              wind_kph: 7.2,
              wind_degree: 274,
              wind_dir: 'W',
              pressure_mb: 1025.0,
              pressure_in: 30.27,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 89,
              cloud: 81,
              feelslike_c: 5.7,
              feelslike_f: 42.3,
              windchill_c: 5.7,
              windchill_f: 42.3,
              heatindex_c: 7.0,
              heatindex_f: 44.6,
              dewpoint_c: 5.4,
              dewpoint_f: 41.7,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 8.1,
              gust_kph: 13.0,
              uv: 1.0,
            },
            {
              time_epoch: 1634097600,
              time: '2021-10-13 06:00',
              temp_c: 7.2,
              temp_f: 45.0,
              is_day: 0,
              condition: {
                text: 'Partly cloudy',
                icon: '//cdn.weatherapi.com/weather/64x64/night/116.png',
                code: 1003,
              },
              wind_mph: 4.9,
              wind_kph: 7.9,
              wind_degree: 267,
              wind_dir: 'W',
              pressure_mb: 1025.0,
              pressure_in: 30.28,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 89,
              cloud: 62,
              feelslike_c: 5.7,
              feelslike_f: 42.3,
              windchill_c: 5.7,
              windchill_f: 42.3,
              heatindex_c: 7.2,
              heatindex_f: 45.0,
              dewpoint_c: 5.5,
              dewpoint_f: 41.9,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 9.2,
              gust_kph: 14.8,
              uv: 1.0,
            },
            {
              time_epoch: 1634101200,
              time: '2021-10-13 07:00',
              temp_c: 7.6,
              temp_f: 45.7,
              is_day: 0,
              condition: {
                text: 'Overcast',
                icon: '//cdn.weatherapi.com/weather/64x64/night/122.png',
                code: 1009,
              },
              wind_mph: 5.8,
              wind_kph: 9.4,
              wind_degree: 261,
              wind_dir: 'W',
              pressure_mb: 1025.0,
              pressure_in: 30.28,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 90,
              cloud: 100,
              feelslike_c: 5.9,
              feelslike_f: 42.6,
              windchill_c: 5.9,
              windchill_f: 42.6,
              heatindex_c: 7.6,
              heatindex_f: 45.7,
              dewpoint_c: 6.0,
              dewpoint_f: 42.8,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 10.5,
              gust_kph: 16.9,
              uv: 1.0,
            },
            {
              time_epoch: 1634104800,
              time: '2021-10-13 08:00',
              temp_c: 8.0,
              temp_f: 46.4,
              is_day: 0,
              condition: {
                text: 'Patchy rain possible',
                icon: '//cdn.weatherapi.com/weather/64x64/night/176.png',
                code: 1063,
              },
              wind_mph: 6.3,
              wind_kph: 10.1,
              wind_degree: 268,
              wind_dir: 'W',
              pressure_mb: 1026.0,
              pressure_in: 30.29,
              precip_mm: 0.1,
              precip_in: 0.0,
              humidity: 90,
              cloud: 100,
              feelslike_c: 6.2,
              feelslike_f: 43.2,
              windchill_c: 6.2,
              windchill_f: 43.2,
              heatindex_c: 8.0,
              heatindex_f: 46.4,
              dewpoint_c: 6.4,
              dewpoint_f: 43.5,
              will_it_rain: 1,
              chance_of_rain: 75,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 10.7,
              gust_kph: 17.3,
              uv: 1.0,
            },
            {
              time_epoch: 1634108400,
              time: '2021-10-13 09:00',
              temp_c: 8.8,
              temp_f: 47.8,
              is_day: 1,
              condition: {
                text: 'Overcast',
                icon: '//cdn.weatherapi.com/weather/64x64/day/122.png',
                code: 1009,
              },
              wind_mph: 6.0,
              wind_kph: 9.7,
              wind_degree: 277,
              wind_dir: 'W',
              pressure_mb: 1026.0,
              pressure_in: 30.3,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 88,
              cloud: 91,
              feelslike_c: 7.2,
              feelslike_f: 45.0,
              windchill_c: 7.2,
              windchill_f: 45.0,
              heatindex_c: 8.8,
              heatindex_f: 47.8,
              dewpoint_c: 6.9,
              dewpoint_f: 44.4,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 9.4,
              gust_kph: 15.1,
              uv: 2.0,
            },
            {
              time_epoch: 1634112000,
              time: '2021-10-13 10:00',
              temp_c: 9.7,
              temp_f: 49.5,
              is_day: 1,
              condition: {
                text: 'Patchy rain possible',
                icon: '//cdn.weatherapi.com/weather/64x64/day/176.png',
                code: 1063,
              },
              wind_mph: 6.5,
              wind_kph: 10.4,
              wind_degree: 287,
              wind_dir: 'WNW',
              pressure_mb: 1026.0,
              pressure_in: 30.31,
              precip_mm: 0.1,
              precip_in: 0.0,
              humidity: 85,
              cloud: 100,
              feelslike_c: 8.2,
              feelslike_f: 46.8,
              windchill_c: 8.2,
              windchill_f: 46.8,
              heatindex_c: 9.7,
              heatindex_f: 49.5,
              dewpoint_c: 7.3,
              dewpoint_f: 45.1,
              will_it_rain: 0,
              chance_of_rain: 59,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 9.2,
              gust_kph: 14.8,
              uv: 2.0,
            },
            {
              time_epoch: 1634115600,
              time: '2021-10-13 11:00',
              temp_c: 10.8,
              temp_f: 51.4,
              is_day: 1,
              condition: {
                text: 'Partly cloudy',
                icon: '//cdn.weatherapi.com/weather/64x64/day/116.png',
                code: 1003,
              },
              wind_mph: 7.8,
              wind_kph: 12.6,
              wind_degree: 299,
              wind_dir: 'WNW',
              pressure_mb: 1027.0,
              pressure_in: 30.31,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 83,
              cloud: 47,
              feelslike_c: 9.2,
              feelslike_f: 48.6,
              windchill_c: 9.2,
              windchill_f: 48.6,
              heatindex_c: 10.8,
              heatindex_f: 51.4,
              dewpoint_c: 8.0,
              dewpoint_f: 46.4,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 9.8,
              gust_kph: 15.8,
              uv: 4.0,
            },
            {
              time_epoch: 1634119200,
              time: '2021-10-13 12:00',
              temp_c: 12.0,
              temp_f: 53.6,
              is_day: 1,
              condition: {
                text: 'Patchy rain possible',
                icon: '//cdn.weatherapi.com/weather/64x64/day/176.png',
                code: 1063,
              },
              wind_mph: 8.7,
              wind_kph: 14.0,
              wind_degree: 313,
              wind_dir: 'NW',
              pressure_mb: 1027.0,
              pressure_in: 30.32,
              precip_mm: 0.1,
              precip_in: 0.0,
              humidity: 76,
              cloud: 79,
              feelslike_c: 10.5,
              feelslike_f: 50.9,
              windchill_c: 10.5,
              windchill_f: 50.9,
              heatindex_c: 12.0,
              heatindex_f: 53.6,
              dewpoint_c: 8.0,
              dewpoint_f: 46.4,
              will_it_rain: 1,
              chance_of_rain: 76,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 10.3,
              gust_kph: 16.6,
              uv: 3.0,
            },
            {
              time_epoch: 1634122800,
              time: '2021-10-13 13:00',
              temp_c: 13.0,
              temp_f: 55.4,
              is_day: 1,
              condition: {
                text: 'Cloudy',
                icon: '//cdn.weatherapi.com/weather/64x64/day/119.png',
                code: 1006,
              },
              wind_mph: 9.4,
              wind_kph: 15.1,
              wind_degree: 315,
              wind_dir: 'NW',
              pressure_mb: 1026.0,
              pressure_in: 30.31,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 68,
              cloud: 65,
              feelslike_c: 11.6,
              feelslike_f: 52.9,
              windchill_c: 11.6,
              windchill_f: 52.9,
              heatindex_c: 13.0,
              heatindex_f: 55.4,
              dewpoint_c: 7.3,
              dewpoint_f: 45.1,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 10.7,
              gust_kph: 17.3,
              uv: 3.0,
            },
            {
              time_epoch: 1634126400,
              time: '2021-10-13 14:00',
              temp_c: 13.4,
              temp_f: 56.1,
              is_day: 1,
              condition: {
                text: 'Patchy rain possible',
                icon: '//cdn.weatherapi.com/weather/64x64/day/176.png',
                code: 1063,
              },
              wind_mph: 9.6,
              wind_kph: 15.5,
              wind_degree: 310,
              wind_dir: 'NW',
              pressure_mb: 1026.0,
              pressure_in: 30.31,
              precip_mm: 0.1,
              precip_in: 0.0,
              humidity: 63,
              cloud: 100,
              feelslike_c: 12.1,
              feelslike_f: 53.8,
              windchill_c: 12.1,
              windchill_f: 53.8,
              heatindex_c: 13.4,
              heatindex_f: 56.1,
              dewpoint_c: 6.5,
              dewpoint_f: 43.7,
              will_it_rain: 1,
              chance_of_rain: 73,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 11.2,
              gust_kph: 18.0,
              uv: 3.0,
            },
            {
              time_epoch: 1634130000,
              time: '2021-10-13 15:00',
              temp_c: 13.2,
              temp_f: 55.8,
              is_day: 1,
              condition: {
                text: 'Overcast',
                icon: '//cdn.weatherapi.com/weather/64x64/day/122.png',
                code: 1009,
              },
              wind_mph: 8.5,
              wind_kph: 13.7,
              wind_degree: 306,
              wind_dir: 'NW',
              pressure_mb: 1026.0,
              pressure_in: 30.31,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 64,
              cloud: 90,
              feelslike_c: 12.0,
              feelslike_f: 53.6,
              windchill_c: 12.0,
              windchill_f: 53.6,
              heatindex_c: 13.2,
              heatindex_f: 55.8,
              dewpoint_c: 6.6,
              dewpoint_f: 43.9,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 9.8,
              gust_kph: 15.8,
              uv: 3.0,
            },
            {
              time_epoch: 1634133600,
              time: '2021-10-13 16:00',
              temp_c: 12.5,
              temp_f: 54.5,
              is_day: 1,
              condition: {
                text: 'Patchy rain possible',
                icon: '//cdn.weatherapi.com/weather/64x64/day/176.png',
                code: 1063,
              },
              wind_mph: 6.9,
              wind_kph: 11.2,
              wind_degree: 304,
              wind_dir: 'NW',
              pressure_mb: 1026.0,
              pressure_in: 30.3,
              precip_mm: 0.1,
              precip_in: 0.0,
              humidity: 65,
              cloud: 73,
              feelslike_c: 11.4,
              feelslike_f: 52.5,
              windchill_c: 11.4,
              windchill_f: 52.5,
              heatindex_c: 12.5,
              heatindex_f: 54.5,
              dewpoint_c: 6.2,
              dewpoint_f: 43.2,
              will_it_rain: 1,
              chance_of_rain: 77,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 9.4,
              gust_kph: 15.1,
              uv: 3.0,
            },
            {
              time_epoch: 1634137200,
              time: '2021-10-13 17:00',
              temp_c: 10.6,
              temp_f: 51.1,
              is_day: 1,
              condition: {
                text: 'Partly cloudy',
                icon: '//cdn.weatherapi.com/weather/64x64/day/116.png',
                code: 1003,
              },
              wind_mph: 5.8,
              wind_kph: 9.4,
              wind_degree: 310,
              wind_dir: 'NW',
              pressure_mb: 1026.0,
              pressure_in: 30.3,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 72,
              cloud: 32,
              feelslike_c: 9.5,
              feelslike_f: 49.1,
              windchill_c: 9.5,
              windchill_f: 49.1,
              heatindex_c: 10.6,
              heatindex_f: 51.1,
              dewpoint_c: 5.8,
              dewpoint_f: 42.4,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 10.5,
              gust_kph: 16.9,
              uv: 4.0,
            },
            {
              time_epoch: 1634140800,
              time: '2021-10-13 18:00',
              temp_c: 8.1,
              temp_f: 46.6,
              is_day: 1,
              condition: {
                text: 'Sunny',
                icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
                code: 1000,
              },
              wind_mph: 4.3,
              wind_kph: 6.8,
              wind_degree: 328,
              wind_dir: 'NNW',
              pressure_mb: 1027.0,
              pressure_in: 30.33,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 76,
              cloud: 18,
              feelslike_c: 7.1,
              feelslike_f: 44.8,
              windchill_c: 7.1,
              windchill_f: 44.8,
              heatindex_c: 8.1,
              heatindex_f: 46.6,
              dewpoint_c: 4.2,
              dewpoint_f: 39.6,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 8.9,
              gust_kph: 14.4,
              uv: 3.0,
            },
            {
              time_epoch: 1634144400,
              time: '2021-10-13 19:00',
              temp_c: 7.2,
              temp_f: 45.0,
              is_day: 0,
              condition: {
                text: 'Clear',
                icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
                code: 1000,
              },
              wind_mph: 2.0,
              wind_kph: 3.2,
              wind_degree: 293,
              wind_dir: 'WNW',
              pressure_mb: 1027.0,
              pressure_in: 30.33,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 78,
              cloud: 22,
              feelslike_c: 7.3,
              feelslike_f: 45.1,
              windchill_c: 7.3,
              windchill_f: 45.1,
              heatindex_c: 7.2,
              heatindex_f: 45.0,
              dewpoint_c: 3.7,
              dewpoint_f: 38.7,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 4.3,
              gust_kph: 6.8,
              uv: 1.0,
            },
            {
              time_epoch: 1634148000,
              time: '2021-10-13 20:00',
              temp_c: 6.0,
              temp_f: 42.8,
              is_day: 0,
              condition: {
                text: 'Partly cloudy',
                icon: '//cdn.weatherapi.com/weather/64x64/night/116.png',
                code: 1003,
              },
              wind_mph: 3.1,
              wind_kph: 5.0,
              wind_degree: 251,
              wind_dir: 'WSW',
              pressure_mb: 1028.0,
              pressure_in: 30.34,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 79,
              cloud: 35,
              feelslike_c: 5.2,
              feelslike_f: 41.4,
              windchill_c: 5.2,
              windchill_f: 41.4,
              heatindex_c: 6.0,
              heatindex_f: 42.8,
              dewpoint_c: 2.7,
              dewpoint_f: 36.9,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 6.5,
              gust_kph: 10.4,
              uv: 1.0,
            },
            {
              time_epoch: 1634151600,
              time: '2021-10-13 21:00',
              temp_c: 5.6,
              temp_f: 42.1,
              is_day: 0,
              condition: {
                text: 'Clear',
                icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
                code: 1000,
              },
              wind_mph: 3.8,
              wind_kph: 6.1,
              wind_degree: 244,
              wind_dir: 'WSW',
              pressure_mb: 1028.0,
              pressure_in: 30.35,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 83,
              cloud: 23,
              feelslike_c: 4.4,
              feelslike_f: 39.9,
              windchill_c: 4.4,
              windchill_f: 39.9,
              heatindex_c: 5.6,
              heatindex_f: 42.1,
              dewpoint_c: 3.0,
              dewpoint_f: 37.4,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 8.1,
              gust_kph: 13.0,
              uv: 1.0,
            },
            {
              time_epoch: 1634155200,
              time: '2021-10-13 22:00',
              temp_c: 5.3,
              temp_f: 41.5,
              is_day: 0,
              condition: {
                text: 'Clear',
                icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
                code: 1000,
              },
              wind_mph: 4.5,
              wind_kph: 7.2,
              wind_degree: 227,
              wind_dir: 'SW',
              pressure_mb: 1028.0,
              pressure_in: 30.36,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 86,
              cloud: 17,
              feelslike_c: 3.7,
              feelslike_f: 38.7,
              windchill_c: 3.7,
              windchill_f: 38.7,
              heatindex_c: 5.3,
              heatindex_f: 41.5,
              dewpoint_c: 3.1,
              dewpoint_f: 37.6,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 9.4,
              gust_kph: 15.1,
              uv: 1.0,
            },
            {
              time_epoch: 1634158800,
              time: '2021-10-13 23:00',
              temp_c: 5.0,
              temp_f: 41.0,
              is_day: 0,
              condition: {
                text: 'Partly cloudy',
                icon: '//cdn.weatherapi.com/weather/64x64/night/116.png',
                code: 1003,
              },
              wind_mph: 5.1,
              wind_kph: 8.3,
              wind_degree: 229,
              wind_dir: 'SW',
              pressure_mb: 1028.0,
              pressure_in: 30.35,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 88,
              cloud: 31,
              feelslike_c: 3.1,
              feelslike_f: 37.6,
              windchill_c: 3.1,
              windchill_f: 37.6,
              heatindex_c: 5.0,
              heatindex_f: 41.0,
              dewpoint_c: 3.2,
              dewpoint_f: 37.8,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 10.7,
              gust_kph: 17.3,
              uv: 1.0,
            },
          ],
        },
        {
          date: '2021-10-14',
          date_epoch: 1634169600,
          day: {
            maxtemp_c: 15.1,
            maxtemp_f: 59.2,
            mintemp_c: 4.3,
            mintemp_f: 39.7,
            avgtemp_c: 8.7,
            avgtemp_f: 47.6,
            maxwind_mph: 9.4,
            maxwind_kph: 15.1,
            totalprecip_mm: 0.0,
            totalprecip_in: 0.0,
            avgvis_km: 10.0,
            avgvis_miles: 6.0,
            avghumidity: 83.0,
            daily_will_it_rain: 0,
            daily_chance_of_rain: 0,
            daily_will_it_snow: 0,
            daily_chance_of_snow: 0,
            condition: {
              text: 'Partly cloudy',
              icon: '//cdn.weatherapi.com/weather/64x64/day/116.png',
              code: 1003,
            },
            uv: 2.0,
          },
          astro: {
            sunrise: '08:02 AM',
            sunset: '06:50 PM',
            moonrise: '05:04 PM',
            moonset: '12:12 AM',
            moon_phase: 'Waxing Gibbous',
            moon_illumination: '62',
          },
          hour: [
            {
              time_epoch: 1634162400,
              time: '2021-10-14 00:00',
              temp_c: 4.9,
              temp_f: 40.8,
              is_day: 0,
              condition: {
                text: 'Partly cloudy',
                icon: '//cdn.weatherapi.com/weather/64x64/night/116.png',
                code: 1003,
              },
              wind_mph: 5.4,
              wind_kph: 8.6,
              wind_degree: 226,
              wind_dir: 'SW',
              pressure_mb: 1028.0,
              pressure_in: 30.35,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 88,
              cloud: 30,
              feelslike_c: 2.8,
              feelslike_f: 37.0,
              windchill_c: 2.8,
              windchill_f: 37.0,
              heatindex_c: 4.9,
              heatindex_f: 40.8,
              dewpoint_c: 3.1,
              dewpoint_f: 37.6,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 11.2,
              gust_kph: 18.0,
              uv: 1.0,
            },
            {
              time_epoch: 1634166000,
              time: '2021-10-14 01:00',
              temp_c: 5.7,
              temp_f: 42.3,
              is_day: 0,
              condition: {
                text: 'Partly cloudy',
                icon: '//cdn.weatherapi.com/weather/64x64/night/116.png',
                code: 1003,
              },
              wind_mph: 5.4,
              wind_kph: 8.6,
              wind_degree: 222,
              wind_dir: 'SW',
              pressure_mb: 1028.0,
              pressure_in: 30.34,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 85,
              cloud: 36,
              feelslike_c: 3.8,
              feelslike_f: 38.8,
              windchill_c: 3.8,
              windchill_f: 38.8,
              heatindex_c: 5.7,
              heatindex_f: 42.3,
              dewpoint_c: 3.4,
              dewpoint_f: 38.1,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 11.2,
              gust_kph: 18.0,
              uv: 1.0,
            },
            {
              time_epoch: 1634169600,
              time: '2021-10-14 02:00',
              temp_c: 6.0,
              temp_f: 42.8,
              is_day: 0,
              condition: {
                text: 'Clear',
                icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
                code: 1000,
              },
              wind_mph: 5.1,
              wind_kph: 8.3,
              wind_degree: 223,
              wind_dir: 'SW',
              pressure_mb: 1027.0,
              pressure_in: 30.34,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 84,
              cloud: 14,
              feelslike_c: 4.2,
              feelslike_f: 39.6,
              windchill_c: 4.2,
              windchill_f: 39.6,
              heatindex_c: 6.0,
              heatindex_f: 42.8,
              dewpoint_c: 3.5,
              dewpoint_f: 38.3,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 10.7,
              gust_kph: 17.3,
              uv: 1.0,
            },
            {
              time_epoch: 1634173200,
              time: '2021-10-14 03:00',
              temp_c: 6.3,
              temp_f: 43.3,
              is_day: 0,
              condition: {
                text: 'Clear',
                icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
                code: 1000,
              },
              wind_mph: 5.4,
              wind_kph: 8.6,
              wind_degree: 225,
              wind_dir: 'SW',
              pressure_mb: 1027.0,
              pressure_in: 30.33,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 82,
              cloud: 12,
              feelslike_c: 4.5,
              feelslike_f: 40.1,
              windchill_c: 4.5,
              windchill_f: 40.1,
              heatindex_c: 6.3,
              heatindex_f: 43.3,
              dewpoint_c: 3.5,
              dewpoint_f: 38.3,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 11.2,
              gust_kph: 18.0,
              uv: 1.0,
            },
            {
              time_epoch: 1634176800,
              time: '2021-10-14 04:00',
              temp_c: 4.8,
              temp_f: 40.6,
              is_day: 0,
              condition: {
                text: 'Partly cloudy',
                icon: '//cdn.weatherapi.com/weather/64x64/night/116.png',
                code: 1003,
              },
              wind_mph: 6.0,
              wind_kph: 9.7,
              wind_degree: 227,
              wind_dir: 'SW',
              pressure_mb: 1027.0,
              pressure_in: 30.32,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 88,
              cloud: 26,
              feelslike_c: 2.5,
              feelslike_f: 36.5,
              windchill_c: 2.5,
              windchill_f: 36.5,
              heatindex_c: 4.8,
              heatindex_f: 40.6,
              dewpoint_c: 2.9,
              dewpoint_f: 37.2,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 12.8,
              gust_kph: 20.5,
              uv: 1.0,
            },
            {
              time_epoch: 1634180400,
              time: '2021-10-14 05:00',
              temp_c: 4.4,
              temp_f: 39.9,
              is_day: 0,
              condition: {
                text: 'Partly cloudy',
                icon: '//cdn.weatherapi.com/weather/64x64/night/116.png',
                code: 1003,
              },
              wind_mph: 6.5,
              wind_kph: 10.4,
              wind_degree: 219,
              wind_dir: 'SW',
              pressure_mb: 1027.0,
              pressure_in: 30.32,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 88,
              cloud: 29,
              feelslike_c: 1.8,
              feelslike_f: 35.2,
              windchill_c: 1.8,
              windchill_f: 35.2,
              heatindex_c: 4.4,
              heatindex_f: 39.9,
              dewpoint_c: 2.5,
              dewpoint_f: 36.5,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 13.6,
              gust_kph: 22.0,
              uv: 1.0,
            },
            {
              time_epoch: 1634184000,
              time: '2021-10-14 06:00',
              temp_c: 4.3,
              temp_f: 39.7,
              is_day: 0,
              condition: {
                text: 'Partly cloudy',
                icon: '//cdn.weatherapi.com/weather/64x64/night/116.png',
                code: 1003,
              },
              wind_mph: 6.7,
              wind_kph: 10.8,
              wind_degree: 213,
              wind_dir: 'SSW',
              pressure_mb: 1027.0,
              pressure_in: 30.32,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 87,
              cloud: 39,
              feelslike_c: 1.6,
              feelslike_f: 34.9,
              windchill_c: 1.6,
              windchill_f: 34.9,
              heatindex_c: 4.3,
              heatindex_f: 39.7,
              dewpoint_c: 2.3,
              dewpoint_f: 36.1,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 14.1,
              gust_kph: 22.7,
              uv: 1.0,
            },
            {
              time_epoch: 1634187600,
              time: '2021-10-14 07:00',
              temp_c: 4.7,
              temp_f: 40.5,
              is_day: 0,
              condition: {
                text: 'Cloudy',
                icon: '//cdn.weatherapi.com/weather/64x64/night/119.png',
                code: 1006,
              },
              wind_mph: 6.9,
              wind_kph: 11.2,
              wind_degree: 212,
              wind_dir: 'SSW',
              pressure_mb: 1027.0,
              pressure_in: 30.32,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 86,
              cloud: 71,
              feelslike_c: 2.1,
              feelslike_f: 35.8,
              windchill_c: 2.1,
              windchill_f: 35.8,
              heatindex_c: 4.7,
              heatindex_f: 40.5,
              dewpoint_c: 2.6,
              dewpoint_f: 36.7,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 14.5,
              gust_kph: 23.4,
              uv: 1.0,
            },
            {
              time_epoch: 1634191200,
              time: '2021-10-14 08:00',
              temp_c: 6.5,
              temp_f: 43.7,
              is_day: 0,
              condition: {
                text: 'Overcast',
                icon: '//cdn.weatherapi.com/weather/64x64/night/122.png',
                code: 1009,
              },
              wind_mph: 7.2,
              wind_kph: 11.5,
              wind_degree: 210,
              wind_dir: 'SSW',
              pressure_mb: 1027.0,
              pressure_in: 30.32,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 84,
              cloud: 100,
              feelslike_c: 4.2,
              feelslike_f: 39.6,
              windchill_c: 4.2,
              windchill_f: 39.6,
              heatindex_c: 6.5,
              heatindex_f: 43.7,
              dewpoint_c: 4.0,
              dewpoint_f: 39.2,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 13.6,
              gust_kph: 22.0,
              uv: 1.0,
            },
            {
              time_epoch: 1634194800,
              time: '2021-10-14 09:00',
              temp_c: 8.8,
              temp_f: 47.8,
              is_day: 1,
              condition: {
                text: 'Overcast',
                icon: '//cdn.weatherapi.com/weather/64x64/day/122.png',
                code: 1009,
              },
              wind_mph: 8.3,
              wind_kph: 13.3,
              wind_degree: 216,
              wind_dir: 'SW',
              pressure_mb: 1027.0,
              pressure_in: 30.32,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 77,
              cloud: 93,
              feelslike_c: 6.7,
              feelslike_f: 44.1,
              windchill_c: 6.7,
              windchill_f: 44.1,
              heatindex_c: 8.8,
              heatindex_f: 47.8,
              dewpoint_c: 5.0,
              dewpoint_f: 41.0,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 12.5,
              gust_kph: 20.2,
              uv: 2.0,
            },
            {
              time_epoch: 1634198400,
              time: '2021-10-14 10:00',
              temp_c: 9.7,
              temp_f: 49.5,
              is_day: 1,
              condition: {
                text: 'Cloudy',
                icon: '//cdn.weatherapi.com/weather/64x64/day/119.png',
                code: 1006,
              },
              wind_mph: 8.7,
              wind_kph: 14.0,
              wind_degree: 216,
              wind_dir: 'SW',
              pressure_mb: 1026.0,
              pressure_in: 30.31,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 77,
              cloud: 85,
              feelslike_c: 7.7,
              feelslike_f: 45.9,
              windchill_c: 7.7,
              windchill_f: 45.9,
              heatindex_c: 9.7,
              heatindex_f: 49.5,
              dewpoint_c: 5.8,
              dewpoint_f: 42.4,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 12.8,
              gust_kph: 20.5,
              uv: 2.0,
            },
            {
              time_epoch: 1634202000,
              time: '2021-10-14 11:00',
              temp_c: 10.9,
              temp_f: 51.6,
              is_day: 1,
              condition: {
                text: 'Cloudy',
                icon: '//cdn.weatherapi.com/weather/64x64/day/119.png',
                code: 1006,
              },
              wind_mph: 8.7,
              wind_kph: 14.0,
              wind_degree: 218,
              wind_dir: 'SW',
              pressure_mb: 1026.0,
              pressure_in: 30.3,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 77,
              cloud: 75,
              feelslike_c: 9.1,
              feelslike_f: 48.4,
              windchill_c: 9.1,
              windchill_f: 48.4,
              heatindex_c: 10.9,
              heatindex_f: 51.6,
              dewpoint_c: 7.1,
              dewpoint_f: 44.8,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 11.4,
              gust_kph: 18.4,
              uv: 3.0,
            },
            {
              time_epoch: 1634205600,
              time: '2021-10-14 12:00',
              temp_c: 11.8,
              temp_f: 53.2,
              is_day: 1,
              condition: {
                text: 'Partly cloudy',
                icon: '//cdn.weatherapi.com/weather/64x64/day/116.png',
                code: 1003,
              },
              wind_mph: 9.2,
              wind_kph: 14.8,
              wind_degree: 229,
              wind_dir: 'SW',
              pressure_mb: 1026.0,
              pressure_in: 30.29,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 77,
              cloud: 61,
              feelslike_c: 10.2,
              feelslike_f: 50.4,
              windchill_c: 10.2,
              windchill_f: 50.4,
              heatindex_c: 11.8,
              heatindex_f: 53.2,
              dewpoint_c: 7.9,
              dewpoint_f: 46.2,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 11.0,
              gust_kph: 17.6,
              uv: 4.0,
            },
            {
              time_epoch: 1634209200,
              time: '2021-10-14 13:00',
              temp_c: 12.8,
              temp_f: 55.0,
              is_day: 1,
              condition: {
                text: 'Partly cloudy',
                icon: '//cdn.weatherapi.com/weather/64x64/day/116.png',
                code: 1003,
              },
              wind_mph: 9.4,
              wind_kph: 15.1,
              wind_degree: 233,
              wind_dir: 'SW',
              pressure_mb: 1025.0,
              pressure_in: 30.26,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 77,
              cloud: 55,
              feelslike_c: 11.3,
              feelslike_f: 52.3,
              windchill_c: 11.3,
              windchill_f: 52.3,
              heatindex_c: 12.8,
              heatindex_f: 55.0,
              dewpoint_c: 8.8,
              dewpoint_f: 47.8,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 10.7,
              gust_kph: 17.3,
              uv: 4.0,
            },
            {
              time_epoch: 1634212800,
              time: '2021-10-14 14:00',
              temp_c: 13.9,
              temp_f: 57.0,
              is_day: 1,
              condition: {
                text: 'Partly cloudy',
                icon: '//cdn.weatherapi.com/weather/64x64/day/116.png',
                code: 1003,
              },
              wind_mph: 9.4,
              wind_kph: 15.1,
              wind_degree: 239,
              wind_dir: 'WSW',
              pressure_mb: 1024.0,
              pressure_in: 30.24,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 76,
              cloud: 37,
              feelslike_c: 12.7,
              feelslike_f: 54.9,
              windchill_c: 12.7,
              windchill_f: 54.9,
              heatindex_c: 13.9,
              heatindex_f: 57.0,
              dewpoint_c: 9.7,
              dewpoint_f: 49.5,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 10.7,
              gust_kph: 17.3,
              uv: 4.0,
            },
            {
              time_epoch: 1634216400,
              time: '2021-10-14 15:00',
              temp_c: 15.1,
              temp_f: 59.2,
              is_day: 1,
              condition: {
                text: 'Partly cloudy',
                icon: '//cdn.weatherapi.com/weather/64x64/day/116.png',
                code: 1003,
              },
              wind_mph: 9.4,
              wind_kph: 15.1,
              wind_degree: 249,
              wind_dir: 'WSW',
              pressure_mb: 1023.0,
              pressure_in: 30.22,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 73,
              cloud: 30,
              feelslike_c: 15.1,
              feelslike_f: 59.2,
              windchill_c: 15.1,
              windchill_f: 59.2,
              heatindex_c: 15.1,
              heatindex_f: 59.2,
              dewpoint_c: 10.2,
              dewpoint_f: 50.4,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 10.7,
              gust_kph: 17.3,
              uv: 5.0,
            },
            {
              time_epoch: 1634220000,
              time: '2021-10-14 16:00',
              temp_c: 14.5,
              temp_f: 58.1,
              is_day: 1,
              condition: {
                text: 'Partly cloudy',
                icon: '//cdn.weatherapi.com/weather/64x64/day/116.png',
                code: 1003,
              },
              wind_mph: 8.7,
              wind_kph: 14.0,
              wind_degree: 254,
              wind_dir: 'WSW',
              pressure_mb: 1023.0,
              pressure_in: 30.2,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 74,
              cloud: 60,
              feelslike_c: 13.6,
              feelslike_f: 56.5,
              windchill_c: 13.6,
              windchill_f: 56.5,
              heatindex_c: 14.5,
              heatindex_f: 58.1,
              dewpoint_c: 10.0,
              dewpoint_f: 50.0,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 11.2,
              gust_kph: 18.0,
              uv: 4.0,
            },
            {
              time_epoch: 1634223600,
              time: '2021-10-14 17:00',
              temp_c: 12.1,
              temp_f: 53.8,
              is_day: 1,
              condition: {
                text: 'Cloudy',
                icon: '//cdn.weatherapi.com/weather/64x64/day/119.png',
                code: 1006,
              },
              wind_mph: 6.9,
              wind_kph: 11.2,
              wind_degree: 247,
              wind_dir: 'WSW',
              pressure_mb: 1022.0,
              pressure_in: 30.19,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 81,
              cloud: 65,
              feelslike_c: 11.0,
              feelslike_f: 51.8,
              windchill_c: 11.0,
              windchill_f: 51.8,
              heatindex_c: 12.1,
              heatindex_f: 53.8,
              dewpoint_c: 9.0,
              dewpoint_f: 48.2,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 12.8,
              gust_kph: 20.5,
              uv: 3.0,
            },
            {
              time_epoch: 1634227200,
              time: '2021-10-14 18:00',
              temp_c: 9.7,
              temp_f: 49.5,
              is_day: 1,
              condition: {
                text: 'Partly cloudy',
                icon: '//cdn.weatherapi.com/weather/64x64/day/116.png',
                code: 1003,
              },
              wind_mph: 6.9,
              wind_kph: 11.2,
              wind_degree: 234,
              wind_dir: 'SW',
              pressure_mb: 1023.0,
              pressure_in: 30.19,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 89,
              cloud: 39,
              feelslike_c: 8.1,
              feelslike_f: 46.6,
              windchill_c: 8.1,
              windchill_f: 46.6,
              heatindex_c: 9.7,
              heatindex_f: 49.5,
              dewpoint_c: 8.0,
              dewpoint_f: 46.4,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 14.5,
              gust_kph: 23.4,
              uv: 3.0,
            },
            {
              time_epoch: 1634230800,
              time: '2021-10-14 19:00',
              temp_c: 8.5,
              temp_f: 47.3,
              is_day: 0,
              condition: {
                text: 'Partly cloudy',
                icon: '//cdn.weatherapi.com/weather/64x64/night/116.png',
                code: 1003,
              },
              wind_mph: 7.2,
              wind_kph: 11.5,
              wind_degree: 220,
              wind_dir: 'SW',
              pressure_mb: 1023.0,
              pressure_in: 30.19,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 91,
              cloud: 30,
              feelslike_c: 6.6,
              feelslike_f: 43.9,
              windchill_c: 6.6,
              windchill_f: 43.9,
              heatindex_c: 8.5,
              heatindex_f: 47.3,
              dewpoint_c: 7.1,
              dewpoint_f: 44.8,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 15.0,
              gust_kph: 24.1,
              uv: 1.0,
            },
            {
              time_epoch: 1634234400,
              time: '2021-10-14 20:00',
              temp_c: 8.3,
              temp_f: 46.9,
              is_day: 0,
              condition: {
                text: 'Partly cloudy',
                icon: '//cdn.weatherapi.com/weather/64x64/night/116.png',
                code: 1003,
              },
              wind_mph: 7.4,
              wind_kph: 11.9,
              wind_degree: 212,
              wind_dir: 'SSW',
              pressure_mb: 1022.0,
              pressure_in: 30.19,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 91,
              cloud: 35,
              feelslike_c: 6.3,
              feelslike_f: 43.3,
              windchill_c: 6.3,
              windchill_f: 43.3,
              heatindex_c: 8.3,
              heatindex_f: 46.9,
              dewpoint_c: 6.9,
              dewpoint_f: 44.4,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 15.4,
              gust_kph: 24.8,
              uv: 1.0,
            },
            {
              time_epoch: 1634238000,
              time: '2021-10-14 21:00',
              temp_c: 8.4,
              temp_f: 47.1,
              is_day: 0,
              condition: {
                text: 'Clear',
                icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
                code: 1000,
              },
              wind_mph: 7.6,
              wind_kph: 12.2,
              wind_degree: 207,
              wind_dir: 'SSW',
              pressure_mb: 1022.0,
              pressure_in: 30.18,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 90,
              cloud: 23,
              feelslike_c: 6.3,
              feelslike_f: 43.3,
              windchill_c: 6.3,
              windchill_f: 43.3,
              heatindex_c: 8.4,
              heatindex_f: 47.1,
              dewpoint_c: 6.9,
              dewpoint_f: 44.4,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 15.9,
              gust_kph: 25.6,
              uv: 1.0,
            },
            {
              time_epoch: 1634241600,
              time: '2021-10-14 22:00',
              temp_c: 8.2,
              temp_f: 46.8,
              is_day: 0,
              condition: {
                text: 'Clear',
                icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
                code: 1000,
              },
              wind_mph: 7.6,
              wind_kph: 12.2,
              wind_degree: 205,
              wind_dir: 'SSW',
              pressure_mb: 1022.0,
              pressure_in: 30.17,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 89,
              cloud: 15,
              feelslike_c: 6.1,
              feelslike_f: 43.0,
              windchill_c: 6.1,
              windchill_f: 43.0,
              heatindex_c: 8.2,
              heatindex_f: 46.8,
              dewpoint_c: 6.5,
              dewpoint_f: 43.7,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 15.9,
              gust_kph: 25.6,
              uv: 1.0,
            },
            {
              time_epoch: 1634245200,
              time: '2021-10-14 23:00',
              temp_c: 7.6,
              temp_f: 45.7,
              is_day: 0,
              condition: {
                text: 'Clear',
                icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
                code: 1000,
              },
              wind_mph: 7.2,
              wind_kph: 11.5,
              wind_degree: 207,
              wind_dir: 'SSW',
              pressure_mb: 1021.0,
              pressure_in: 30.16,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 89,
              cloud: 11,
              feelslike_c: 5.5,
              feelslike_f: 41.9,
              windchill_c: 5.5,
              windchill_f: 41.9,
              heatindex_c: 7.6,
              heatindex_f: 45.7,
              dewpoint_c: 6.0,
              dewpoint_f: 42.8,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 15.0,
              gust_kph: 24.1,
              uv: 1.0,
            },
          ],
        },
        {
          date: '2021-10-15',
          date_epoch: 1634256000,
          day: {
            maxtemp_c: 14.4,
            maxtemp_f: 57.9,
            mintemp_c: 6.7,
            mintemp_f: 44.1,
            avgtemp_c: 9.7,
            avgtemp_f: 49.4,
            maxwind_mph: 9.2,
            maxwind_kph: 14.8,
            totalprecip_mm: 0.6,
            totalprecip_in: 0.02,
            avgvis_km: 9.7,
            avgvis_miles: 6.0,
            avghumidity: 86.0,
            daily_will_it_rain: 1,
            daily_chance_of_rain: 78,
            daily_will_it_snow: 0,
            daily_chance_of_snow: 0,
            condition: {
              text: 'Patchy rain possible',
              icon: '//cdn.weatherapi.com/weather/64x64/day/176.png',
              code: 1063,
            },
            uv: 1.0,
          },
          astro: {
            sunrise: '08:03 AM',
            sunset: '06:48 PM',
            moonrise: '05:31 PM',
            moonset: '01:30 AM',
            moon_phase: 'Waxing Gibbous',
            moon_illumination: '69',
          },
          hour: [
            {
              time_epoch: 1634248800,
              time: '2021-10-15 00:00',
              temp_c: 7.4,
              temp_f: 45.3,
              is_day: 0,
              condition: {
                text: 'Clear',
                icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
                code: 1000,
              },
              wind_mph: 7.6,
              wind_kph: 12.2,
              wind_degree: 207,
              wind_dir: 'SSW',
              pressure_mb: 1021.0,
              pressure_in: 30.14,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 89,
              cloud: 10,
              feelslike_c: 5.1,
              feelslike_f: 41.2,
              windchill_c: 5.1,
              windchill_f: 41.2,
              heatindex_c: 7.4,
              heatindex_f: 45.3,
              dewpoint_c: 5.7,
              dewpoint_f: 42.3,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 15.9,
              gust_kph: 25.6,
              uv: 1.0,
            },
            {
              time_epoch: 1634252400,
              time: '2021-10-15 01:00',
              temp_c: 7.2,
              temp_f: 45.0,
              is_day: 0,
              condition: {
                text: 'Clear',
                icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
                code: 1000,
              },
              wind_mph: 7.6,
              wind_kph: 12.2,
              wind_degree: 207,
              wind_dir: 'SSW',
              pressure_mb: 1020.0,
              pressure_in: 30.12,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 88,
              cloud: 10,
              feelslike_c: 4.9,
              feelslike_f: 40.8,
              windchill_c: 4.9,
              windchill_f: 40.8,
              heatindex_c: 7.2,
              heatindex_f: 45.0,
              dewpoint_c: 5.4,
              dewpoint_f: 41.7,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 15.9,
              gust_kph: 25.6,
              uv: 1.0,
            },
            {
              time_epoch: 1634256000,
              time: '2021-10-15 02:00',
              temp_c: 7.3,
              temp_f: 45.1,
              is_day: 0,
              condition: {
                text: 'Clear',
                icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
                code: 1000,
              },
              wind_mph: 7.4,
              wind_kph: 11.9,
              wind_degree: 212,
              wind_dir: 'SSW',
              pressure_mb: 1020.0,
              pressure_in: 30.11,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 88,
              cloud: 12,
              feelslike_c: 5.1,
              feelslike_f: 41.2,
              windchill_c: 5.1,
              windchill_f: 41.2,
              heatindex_c: 7.3,
              heatindex_f: 45.1,
              dewpoint_c: 5.4,
              dewpoint_f: 41.7,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 15.4,
              gust_kph: 24.8,
              uv: 1.0,
            },
            {
              time_epoch: 1634259600,
              time: '2021-10-15 03:00',
              temp_c: 7.2,
              temp_f: 45.0,
              is_day: 0,
              condition: {
                text: 'Clear',
                icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
                code: 1000,
              },
              wind_mph: 7.6,
              wind_kph: 12.2,
              wind_degree: 213,
              wind_dir: 'SSW',
              pressure_mb: 1019.0,
              pressure_in: 30.09,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 87,
              cloud: 13,
              feelslike_c: 4.9,
              feelslike_f: 40.8,
              windchill_c: 4.9,
              windchill_f: 40.8,
              heatindex_c: 7.2,
              heatindex_f: 45.0,
              dewpoint_c: 5.2,
              dewpoint_f: 41.4,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 15.9,
              gust_kph: 25.6,
              uv: 1.0,
            },
            {
              time_epoch: 1634263200,
              time: '2021-10-15 04:00',
              temp_c: 7.1,
              temp_f: 44.8,
              is_day: 0,
              condition: {
                text: 'Clear',
                icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
                code: 1000,
              },
              wind_mph: 8.1,
              wind_kph: 13.0,
              wind_degree: 215,
              wind_dir: 'SW',
              pressure_mb: 1019.0,
              pressure_in: 30.09,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 87,
              cloud: 10,
              feelslike_c: 4.6,
              feelslike_f: 40.3,
              windchill_c: 4.6,
              windchill_f: 40.3,
              heatindex_c: 7.1,
              heatindex_f: 44.8,
              dewpoint_c: 5.0,
              dewpoint_f: 41.0,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 16.8,
              gust_kph: 27.0,
              uv: 1.0,
            },
            {
              time_epoch: 1634266800,
              time: '2021-10-15 05:00',
              temp_c: 7.1,
              temp_f: 44.8,
              is_day: 0,
              condition: {
                text: 'Clear',
                icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
                code: 1000,
              },
              wind_mph: 8.3,
              wind_kph: 13.3,
              wind_degree: 218,
              wind_dir: 'SW',
              pressure_mb: 1019.0,
              pressure_in: 30.08,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 86,
              cloud: 9,
              feelslike_c: 4.6,
              feelslike_f: 40.3,
              windchill_c: 4.6,
              windchill_f: 40.3,
              heatindex_c: 7.1,
              heatindex_f: 44.8,
              dewpoint_c: 4.9,
              dewpoint_f: 40.8,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 16.8,
              gust_kph: 27.0,
              uv: 1.0,
            },
            {
              time_epoch: 1634270400,
              time: '2021-10-15 06:00',
              temp_c: 6.7,
              temp_f: 44.1,
              is_day: 0,
              condition: {
                text: 'Clear',
                icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
                code: 1000,
              },
              wind_mph: 7.6,
              wind_kph: 12.2,
              wind_degree: 215,
              wind_dir: 'SW',
              pressure_mb: 1019.0,
              pressure_in: 30.08,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 86,
              cloud: 10,
              feelslike_c: 4.3,
              feelslike_f: 39.7,
              windchill_c: 4.3,
              windchill_f: 39.7,
              heatindex_c: 6.7,
              heatindex_f: 44.1,
              dewpoint_c: 4.6,
              dewpoint_f: 40.3,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 15.9,
              gust_kph: 25.6,
              uv: 1.0,
            },
            {
              time_epoch: 1634274000,
              time: '2021-10-15 07:00',
              temp_c: 6.7,
              temp_f: 44.1,
              is_day: 0,
              condition: {
                text: 'Clear',
                icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
                code: 1000,
              },
              wind_mph: 7.8,
              wind_kph: 12.6,
              wind_degree: 213,
              wind_dir: 'SSW',
              pressure_mb: 1018.0,
              pressure_in: 30.07,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 85,
              cloud: 13,
              feelslike_c: 4.2,
              feelslike_f: 39.6,
              windchill_c: 4.2,
              windchill_f: 39.6,
              heatindex_c: 6.7,
              heatindex_f: 44.1,
              dewpoint_c: 4.4,
              dewpoint_f: 39.9,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 16.3,
              gust_kph: 26.3,
              uv: 1.0,
            },
            {
              time_epoch: 1634277600,
              time: '2021-10-15 08:00',
              temp_c: 7.7,
              temp_f: 45.9,
              is_day: 0,
              condition: {
                text: 'Partly cloudy',
                icon: '//cdn.weatherapi.com/weather/64x64/night/116.png',
                code: 1003,
              },
              wind_mph: 7.4,
              wind_kph: 11.9,
              wind_degree: 217,
              wind_dir: 'SW',
              pressure_mb: 1019.0,
              pressure_in: 30.08,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 82,
              cloud: 49,
              feelslike_c: 5.5,
              feelslike_f: 41.9,
              windchill_c: 5.5,
              windchill_f: 41.9,
              heatindex_c: 7.7,
              heatindex_f: 45.9,
              dewpoint_c: 4.8,
              dewpoint_f: 40.6,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 13.6,
              gust_kph: 22.0,
              uv: 1.0,
            },
            {
              time_epoch: 1634281200,
              time: '2021-10-15 09:00',
              temp_c: 9.5,
              temp_f: 49.1,
              is_day: 1,
              condition: {
                text: 'Overcast',
                icon: '//cdn.weatherapi.com/weather/64x64/day/122.png',
                code: 1009,
              },
              wind_mph: 8.1,
              wind_kph: 13.0,
              wind_degree: 226,
              wind_dir: 'SW',
              pressure_mb: 1019.0,
              pressure_in: 30.08,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 77,
              cloud: 100,
              feelslike_c: 7.6,
              feelslike_f: 45.7,
              windchill_c: 7.6,
              windchill_f: 45.7,
              heatindex_c: 9.5,
              heatindex_f: 49.1,
              dewpoint_c: 5.7,
              dewpoint_f: 42.3,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 11.9,
              gust_kph: 19.1,
              uv: 2.0,
            },
            {
              time_epoch: 1634284800,
              time: '2021-10-15 10:00',
              temp_c: 11.2,
              temp_f: 52.2,
              is_day: 1,
              condition: {
                text: 'Overcast',
                icon: '//cdn.weatherapi.com/weather/64x64/day/122.png',
                code: 1009,
              },
              wind_mph: 8.7,
              wind_kph: 14.0,
              wind_degree: 247,
              wind_dir: 'WSW',
              pressure_mb: 1019.0,
              pressure_in: 30.09,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 76,
              cloud: 100,
              feelslike_c: 9.5,
              feelslike_f: 49.1,
              windchill_c: 9.5,
              windchill_f: 49.1,
              heatindex_c: 11.2,
              heatindex_f: 52.2,
              dewpoint_c: 7.1,
              dewpoint_f: 44.8,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 10.7,
              gust_kph: 17.3,
              uv: 3.0,
            },
            {
              time_epoch: 1634288400,
              time: '2021-10-15 11:00',
              temp_c: 12.7,
              temp_f: 54.9,
              is_day: 1,
              condition: {
                text: 'Overcast',
                icon: '//cdn.weatherapi.com/weather/64x64/day/122.png',
                code: 1009,
              },
              wind_mph: 9.2,
              wind_kph: 14.8,
              wind_degree: 254,
              wind_dir: 'WSW',
              pressure_mb: 1019.0,
              pressure_in: 30.09,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 78,
              cloud: 100,
              feelslike_c: 11.3,
              feelslike_f: 52.3,
              windchill_c: 11.3,
              windchill_f: 52.3,
              heatindex_c: 12.7,
              heatindex_f: 54.9,
              dewpoint_c: 9.0,
              dewpoint_f: 48.2,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 10.5,
              gust_kph: 16.9,
              uv: 3.0,
            },
            {
              time_epoch: 1634292000,
              time: '2021-10-15 12:00',
              temp_c: 13.9,
              temp_f: 57.0,
              is_day: 1,
              condition: {
                text: 'Overcast',
                icon: '//cdn.weatherapi.com/weather/64x64/day/122.png',
                code: 1009,
              },
              wind_mph: 8.7,
              wind_kph: 14.0,
              wind_degree: 267,
              wind_dir: 'W',
              pressure_mb: 1019.0,
              pressure_in: 30.09,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 79,
              cloud: 100,
              feelslike_c: 12.8,
              feelslike_f: 55.0,
              windchill_c: 12.8,
              windchill_f: 55.0,
              heatindex_c: 13.9,
              heatindex_f: 57.0,
              dewpoint_c: 10.4,
              dewpoint_f: 50.7,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 10.1,
              gust_kph: 16.2,
              uv: 3.0,
            },
            {
              time_epoch: 1634295600,
              time: '2021-10-15 13:00',
              temp_c: 14.4,
              temp_f: 57.9,
              is_day: 1,
              condition: {
                text: 'Overcast',
                icon: '//cdn.weatherapi.com/weather/64x64/day/122.png',
                code: 1009,
              },
              wind_mph: 8.1,
              wind_kph: 13.0,
              wind_degree: 276,
              wind_dir: 'W',
              pressure_mb: 1019.0,
              pressure_in: 30.09,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 78,
              cloud: 100,
              feelslike_c: 13.5,
              feelslike_f: 56.3,
              windchill_c: 13.5,
              windchill_f: 56.3,
              heatindex_c: 14.4,
              heatindex_f: 57.9,
              dewpoint_c: 10.6,
              dewpoint_f: 51.1,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 9.2,
              gust_kph: 14.8,
              uv: 3.0,
            },
            {
              time_epoch: 1634299200,
              time: '2021-10-15 14:00',
              temp_c: 14.3,
              temp_f: 57.7,
              is_day: 1,
              condition: {
                text: 'Patchy rain possible',
                icon: '//cdn.weatherapi.com/weather/64x64/day/176.png',
                code: 1063,
              },
              wind_mph: 7.2,
              wind_kph: 11.5,
              wind_degree: 284,
              wind_dir: 'WNW',
              pressure_mb: 1019.0,
              pressure_in: 30.08,
              precip_mm: 0.1,
              precip_in: 0.0,
              humidity: 76,
              cloud: 100,
              feelslike_c: 13.6,
              feelslike_f: 56.5,
              windchill_c: 13.6,
              windchill_f: 56.5,
              heatindex_c: 14.3,
              heatindex_f: 57.7,
              dewpoint_c: 10.1,
              dewpoint_f: 50.2,
              will_it_rain: 0,
              chance_of_rain: 68,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 8.5,
              gust_kph: 13.7,
              uv: 3.0,
            },
            {
              time_epoch: 1634302800,
              time: '2021-10-15 15:00',
              temp_c: 13.5,
              temp_f: 56.3,
              is_day: 1,
              condition: {
                text: 'Overcast',
                icon: '//cdn.weatherapi.com/weather/64x64/day/122.png',
                code: 1009,
              },
              wind_mph: 7.2,
              wind_kph: 11.5,
              wind_degree: 333,
              wind_dir: 'NNW',
              pressure_mb: 1019.0,
              pressure_in: 30.09,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 82,
              cloud: 100,
              feelslike_c: 12.6,
              feelslike_f: 54.7,
              windchill_c: 12.6,
              windchill_f: 54.7,
              heatindex_c: 13.5,
              heatindex_f: 56.3,
              dewpoint_c: 10.5,
              dewpoint_f: 50.9,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 8.9,
              gust_kph: 14.4,
              uv: 3.0,
            },
            {
              time_epoch: 1634306400,
              time: '2021-10-15 16:00',
              temp_c: 11.7,
              temp_f: 53.1,
              is_day: 1,
              condition: {
                text: 'Light rain shower',
                icon: '//cdn.weatherapi.com/weather/64x64/day/353.png',
                code: 1240,
              },
              wind_mph: 8.9,
              wind_kph: 14.4,
              wind_degree: 26,
              wind_dir: 'NNE',
              pressure_mb: 1019.0,
              pressure_in: 30.1,
              precip_mm: 0.4,
              precip_in: 0.02,
              humidity: 91,
              cloud: 100,
              feelslike_c: 10.1,
              feelslike_f: 50.2,
              windchill_c: 10.1,
              windchill_f: 50.2,
              heatindex_c: 11.7,
              heatindex_f: 53.1,
              dewpoint_c: 10.3,
              dewpoint_f: 50.5,
              will_it_rain: 1,
              chance_of_rain: 78,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 10.7,
              gust_kph: 17.3,
              uv: 3.0,
            },
            {
              time_epoch: 1634310000,
              time: '2021-10-15 17:00',
              temp_c: 10.8,
              temp_f: 51.4,
              is_day: 1,
              condition: {
                text: 'Overcast',
                icon: '//cdn.weatherapi.com/weather/64x64/day/122.png',
                code: 1009,
              },
              wind_mph: 7.4,
              wind_kph: 11.9,
              wind_degree: 39,
              wind_dir: 'NE',
              pressure_mb: 1020.0,
              pressure_in: 30.12,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 93,
              cloud: 100,
              feelslike_c: 9.3,
              feelslike_f: 48.7,
              windchill_c: 9.3,
              windchill_f: 48.7,
              heatindex_c: 10.8,
              heatindex_f: 51.4,
              dewpoint_c: 9.7,
              dewpoint_f: 49.5,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 9.4,
              gust_kph: 15.1,
              uv: 3.0,
            },
            {
              time_epoch: 1634313600,
              time: '2021-10-15 18:00',
              temp_c: 10.2,
              temp_f: 50.4,
              is_day: 1,
              condition: {
                text: 'Patchy rain possible',
                icon: '//cdn.weatherapi.com/weather/64x64/day/176.png',
                code: 1063,
              },
              wind_mph: 5.4,
              wind_kph: 8.6,
              wind_degree: 48,
              wind_dir: 'NE',
              pressure_mb: 1021.0,
              pressure_in: 30.14,
              precip_mm: 0.1,
              precip_in: 0.0,
              humidity: 93,
              cloud: 90,
              feelslike_c: 9.1,
              feelslike_f: 48.4,
              windchill_c: 9.1,
              windchill_f: 48.4,
              heatindex_c: 10.2,
              heatindex_f: 50.4,
              dewpoint_c: 9.1,
              dewpoint_f: 48.4,
              will_it_rain: 1,
              chance_of_rain: 71,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 7.6,
              gust_kph: 12.2,
              uv: 3.0,
            },
            {
              time_epoch: 1634317200,
              time: '2021-10-15 19:00',
              temp_c: 10.2,
              temp_f: 50.4,
              is_day: 0,
              condition: {
                text: 'Partly cloudy',
                icon: '//cdn.weatherapi.com/weather/64x64/night/116.png',
                code: 1003,
              },
              wind_mph: 4.5,
              wind_kph: 7.2,
              wind_degree: 60,
              wind_dir: 'ENE',
              pressure_mb: 1021.0,
              pressure_in: 30.16,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 93,
              cloud: 39,
              feelslike_c: 9.4,
              feelslike_f: 48.9,
              windchill_c: 9.4,
              windchill_f: 48.9,
              heatindex_c: 10.2,
              heatindex_f: 50.4,
              dewpoint_c: 9.1,
              dewpoint_f: 48.4,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 6.3,
              gust_kph: 10.1,
              uv: 1.0,
            },
            {
              time_epoch: 1634320800,
              time: '2021-10-15 20:00',
              temp_c: 9.5,
              temp_f: 49.1,
              is_day: 0,
              condition: {
                text: 'Partly cloudy',
                icon: '//cdn.weatherapi.com/weather/64x64/night/116.png',
                code: 1003,
              },
              wind_mph: 4.0,
              wind_kph: 6.5,
              wind_degree: 63,
              wind_dir: 'ENE',
              pressure_mb: 1022.0,
              pressure_in: 30.16,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 94,
              cloud: 33,
              feelslike_c: 8.8,
              feelslike_f: 47.8,
              windchill_c: 8.8,
              windchill_f: 47.8,
              heatindex_c: 9.5,
              heatindex_f: 49.1,
              dewpoint_c: 8.5,
              dewpoint_f: 47.3,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 6.5,
              gust_kph: 10.4,
              uv: 1.0,
            },
            {
              time_epoch: 1634324400,
              time: '2021-10-15 21:00',
              temp_c: 9.5,
              temp_f: 49.1,
              is_day: 0,
              condition: {
                text: 'Clear',
                icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
                code: 1000,
              },
              wind_mph: 4.0,
              wind_kph: 6.5,
              wind_degree: 73,
              wind_dir: 'ENE',
              pressure_mb: 1022.0,
              pressure_in: 30.17,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 93,
              cloud: 24,
              feelslike_c: 8.8,
              feelslike_f: 47.8,
              windchill_c: 8.8,
              windchill_f: 47.8,
              heatindex_c: 9.5,
              heatindex_f: 49.1,
              dewpoint_c: 8.5,
              dewpoint_f: 47.3,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 6.5,
              gust_kph: 10.4,
              uv: 1.0,
            },
            {
              time_epoch: 1634328000,
              time: '2021-10-15 22:00',
              temp_c: 8.7,
              temp_f: 47.7,
              is_day: 0,
              condition: {
                text: 'Clear',
                icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
                code: 1000,
              },
              wind_mph: 4.5,
              wind_kph: 7.2,
              wind_degree: 52,
              wind_dir: 'NE',
              pressure_mb: 1022.0,
              pressure_in: 30.18,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 93,
              cloud: 19,
              feelslike_c: 7.7,
              feelslike_f: 45.9,
              windchill_c: 7.7,
              windchill_f: 45.9,
              heatindex_c: 8.7,
              heatindex_f: 47.7,
              dewpoint_c: 7.7,
              dewpoint_f: 45.9,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 8.1,
              gust_kph: 13.0,
              uv: 1.0,
            },
            {
              time_epoch: 1634331600,
              time: '2021-10-15 23:00',
              temp_c: 7.2,
              temp_f: 45.0,
              is_day: 0,
              condition: {
                text: 'Mist',
                icon: '//cdn.weatherapi.com/weather/64x64/night/143.png',
                code: 1030,
              },
              wind_mph: 4.9,
              wind_kph: 7.9,
              wind_degree: 47,
              wind_dir: 'NE',
              pressure_mb: 1022.0,
              pressure_in: 30.19,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 95,
              cloud: 25,
              feelslike_c: 5.7,
              feelslike_f: 42.3,
              windchill_c: 5.7,
              windchill_f: 42.3,
              heatindex_c: 7.2,
              heatindex_f: 45.0,
              dewpoint_c: 6.4,
              dewpoint_f: 43.5,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 2.0,
              vis_miles: 1.0,
              gust_mph: 10.1,
              gust_kph: 16.2,
              uv: 1.0,
            },
          ],
        },
      ],
    },
  },
];
